// Code generated by protoc-gen-go. DO NOT EDIT.
// source: sensor.proto

package sensor

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Dht22 struct {
	Temperature          float32  `protobuf:"fixed32,1,opt,name=Temperature,proto3" json:"Temperature,omitempty"`
	Humidity             float32  `protobuf:"fixed32,2,opt,name=Humidity,proto3" json:"Humidity,omitempty"`
	RetryCount           int32    `protobuf:"varint,3,opt,name=RetryCount,proto3" json:"RetryCount,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Dht22) Reset()         { *m = Dht22{} }
func (m *Dht22) String() string { return proto.CompactTextString(m) }
func (*Dht22) ProtoMessage()    {}
func (*Dht22) Descriptor() ([]byte, []int) {
	return fileDescriptor_sensor_1708a4f29065c234, []int{0}
}
func (m *Dht22) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Dht22.Unmarshal(m, b)
}
func (m *Dht22) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Dht22.Marshal(b, m, deterministic)
}
func (dst *Dht22) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Dht22.Merge(dst, src)
}
func (m *Dht22) XXX_Size() int {
	return xxx_messageInfo_Dht22.Size(m)
}
func (m *Dht22) XXX_DiscardUnknown() {
	xxx_messageInfo_Dht22.DiscardUnknown(m)
}

var xxx_messageInfo_Dht22 proto.InternalMessageInfo

func (m *Dht22) GetTemperature() float32 {
	if m != nil {
		return m.Temperature
	}
	return 0
}

func (m *Dht22) GetHumidity() float32 {
	if m != nil {
		return m.Humidity
	}
	return 0
}

func (m *Dht22) GetRetryCount() int32 {
	if m != nil {
		return m.RetryCount
	}
	return 0
}

type SensorReading struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Location             string   `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	Dht22                *Dht22   `protobuf:"bytes,3,opt,name=dht22,proto3" json:"dht22,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SensorReading) Reset()         { *m = SensorReading{} }
func (m *SensorReading) String() string { return proto.CompactTextString(m) }
func (*SensorReading) ProtoMessage()    {}
func (*SensorReading) Descriptor() ([]byte, []int) {
	return fileDescriptor_sensor_1708a4f29065c234, []int{1}
}
func (m *SensorReading) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SensorReading.Unmarshal(m, b)
}
func (m *SensorReading) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SensorReading.Marshal(b, m, deterministic)
}
func (dst *SensorReading) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SensorReading.Merge(dst, src)
}
func (m *SensorReading) XXX_Size() int {
	return xxx_messageInfo_SensorReading.Size(m)
}
func (m *SensorReading) XXX_DiscardUnknown() {
	xxx_messageInfo_SensorReading.DiscardUnknown(m)
}

var xxx_messageInfo_SensorReading proto.InternalMessageInfo

func (m *SensorReading) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SensorReading) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *SensorReading) GetDht22() *Dht22 {
	if m != nil {
		return m.Dht22
	}
	return nil
}

func init() {
	proto.RegisterType((*Dht22)(nil), "sensor.Dht22")
	proto.RegisterType((*SensorReading)(nil), "sensor.SensorReading")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SensorReportingServiceClient is the client API for SensorReportingService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SensorReportingServiceClient interface {
	StreamReadings(ctx context.Context, opts ...grpc.CallOption) (SensorReportingService_StreamReadingsClient, error)
}

type sensorReportingServiceClient struct {
	cc *grpc.ClientConn
}

func NewSensorReportingServiceClient(cc *grpc.ClientConn) SensorReportingServiceClient {
	return &sensorReportingServiceClient{cc}
}

func (c *sensorReportingServiceClient) StreamReadings(ctx context.Context, opts ...grpc.CallOption) (SensorReportingService_StreamReadingsClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SensorReportingService_serviceDesc.Streams[0], "/sensor.SensorReportingService/StreamReadings", opts...)
	if err != nil {
		return nil, err
	}
	x := &sensorReportingServiceStreamReadingsClient{stream}
	return x, nil
}

type SensorReportingService_StreamReadingsClient interface {
	Send(*SensorReading) error
	CloseAndRecv() (*empty.Empty, error)
	grpc.ClientStream
}

type sensorReportingServiceStreamReadingsClient struct {
	grpc.ClientStream
}

func (x *sensorReportingServiceStreamReadingsClient) Send(m *SensorReading) error {
	return x.ClientStream.SendMsg(m)
}

func (x *sensorReportingServiceStreamReadingsClient) CloseAndRecv() (*empty.Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(empty.Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SensorReportingServiceServer is the server API for SensorReportingService service.
type SensorReportingServiceServer interface {
	StreamReadings(SensorReportingService_StreamReadingsServer) error
}

func RegisterSensorReportingServiceServer(s *grpc.Server, srv SensorReportingServiceServer) {
	s.RegisterService(&_SensorReportingService_serviceDesc, srv)
}

func _SensorReportingService_StreamReadings_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SensorReportingServiceServer).StreamReadings(&sensorReportingServiceStreamReadingsServer{stream})
}

type SensorReportingService_StreamReadingsServer interface {
	SendAndClose(*empty.Empty) error
	Recv() (*SensorReading, error)
	grpc.ServerStream
}

type sensorReportingServiceStreamReadingsServer struct {
	grpc.ServerStream
}

func (x *sensorReportingServiceStreamReadingsServer) SendAndClose(m *empty.Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *sensorReportingServiceStreamReadingsServer) Recv() (*SensorReading, error) {
	m := new(SensorReading)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SensorReportingService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "sensor.SensorReportingService",
	HandlerType: (*SensorReportingServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamReadings",
			Handler:       _SensorReportingService_StreamReadings_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "sensor.proto",
}

func init() { proto.RegisterFile("sensor.proto", fileDescriptor_sensor_1708a4f29065c234) }

var fileDescriptor_sensor_1708a4f29065c234 = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x24, 0xc5, 0x4e, 0x6d, 0x0f, 0x0b, 0x96, 0x10, 0x41, 0x42, 0xbd, 0xe4, 0xb4,
	0x85, 0xf8, 0x0b, 0x44, 0x05, 0x0b, 0x9e, 0x36, 0xde, 0xbc, 0x98, 0x76, 0xc7, 0xb8, 0x60, 0x76,
	0xc2, 0x66, 0x22, 0xe4, 0xdf, 0x4b, 0x36, 0x4d, 0x69, 0x8f, 0xef, 0xcd, 0xf2, 0xde, 0xb7, 0x0f,
	0x6e, 0x5a, 0xb4, 0x2d, 0x39, 0xd9, 0x38, 0x62, 0x12, 0xb3, 0x51, 0x25, 0x77, 0x15, 0x51, 0xf5,
	0x8b, 0x5b, 0xef, 0xee, 0xbb, 0xef, 0x2d, 0xd6, 0x0d, 0xf7, 0xe3, 0xa3, 0x0d, 0x42, 0xf4, 0xf2,
	0xc3, 0x79, 0x2e, 0x52, 0x58, 0x7c, 0x60, 0xdd, 0xa0, 0x2b, 0xb9, 0x73, 0x18, 0x07, 0x69, 0x90,
	0x85, 0xea, 0xdc, 0x12, 0x09, 0x5c, 0xbf, 0x75, 0xb5, 0xd1, 0x86, 0xfb, 0x38, 0xf4, 0xe7, 0x93,
	0x16, 0xf7, 0x00, 0x0a, 0xd9, 0xf5, 0xcf, 0xd4, 0x59, 0x8e, 0xaf, 0xd2, 0x20, 0x8b, 0xd4, 0x99,
	0xb3, 0xf9, 0x82, 0x65, 0xe1, 0x69, 0x14, 0x96, 0xda, 0xd8, 0x4a, 0xac, 0x20, 0xdc, 0x69, 0xdf,
	0x32, 0x57, 0xe1, 0x4e, 0x0f, 0xe1, 0xef, 0x74, 0x28, 0xd9, 0x90, 0xf5, 0xe1, 0x73, 0x75, 0xd2,
	0xe2, 0x01, 0x22, 0x3d, 0x30, 0xfa, 0xdc, 0x45, 0xbe, 0x94, 0xc7, 0x6f, 0x7a, 0x70, 0x35, 0xde,
	0xf2, 0x4f, 0x58, 0x4f, 0x0d, 0x0d, 0x39, 0x36, 0xb6, 0x2a, 0xd0, 0xfd, 0x99, 0x03, 0x8a, 0x27,
	0x58, 0x15, 0xec, 0xb0, 0xac, 0x8f, 0xdd, 0xad, 0xb8, 0x9d, 0x12, 0x2e, 0x98, 0x92, 0xb5, 0x1c,
	0x97, 0x92, 0xd3, 0x52, 0xf2, 0x75, 0x58, 0x2a, 0x0b, 0xf6, 0x33, 0xef, 0x3c, 0xfe, 0x07, 0x00,
	0x00, 0xff, 0xff, 0xef, 0xd7, 0x2f, 0x3a, 0x61, 0x01, 0x00, 0x00,
}
